# Práctica Clase 3

## Numpy

In [2]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [ ]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [ ]:
arreglo = np.arange(8)
print(arreglo)

Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [ ]:
lista + 1

In [ ]:
arreglo = arreglo + 1

In [ ]:
arreglo

2. Elevar al cuadrado todos los elementos

In [ ]:
lista**2

In [ ]:
arreglo**2

3. Sumar todos los elementos

In [ ]:
print(arreglo.sum())
print(lista.sum())

In [ ]:
n = 0
for e in lista:
    n = n + e
print(n)

In [ ]:
arreglo.shape

In [ ]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

In [ ]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


In [ ]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

In [ ]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

In [ ]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

In [ ]:
a3 = a1 * a2
a3.shape

In [ ]:
a3

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [ ]:
# ejercicio 2
arr1 = np.arange(10) 
arr2 = np.linspace(0,9,100)
print(arr1)
print('-'*30)
print(arr2)

In [ ]:
#ejercicio3
arr3 = np.arange(10,101)
mascara = ((arr3 % 3) == 0 )
print(arr3[mascara])

In [17]:
#Ejercicio 4
arr4 = np.zeros((5,10))
arr4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
# LE PUEDO PASAR UNA LISTA CON LOS INDICES QUE QUIERO
arr4[[1,3]] = 1 
arr4[:,[2,7]] = 2
arr4

array([[0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.]])

array([[0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.]])

In [ ]:
arr4[1:2] = 1
arr4[3:4] = 1

In [ ]:
arr4[::,2:3] = 2
arr4[::,7:8] = 2

In [1]:
arr4

NameError: name 'arr4' is not defined

In [ ]:
#  Replace all odd numbers in arr with -1}
mascara = ((arr1 % 2) == 0)
arr1[mascara == False] = -1
arr1

In [ ]:
arr1 = np.arange(10)
print(np.where(arr1 % 2 == 1,-1,arr1))

In [ ]:
#Convert a 1D array to a 2D array with 2 rows

matriz = arr1.reshape(2,5)
matriz

In [ ]:
#Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b],axis=1)

In [ ]:
#Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
a = np.array([1,2,3])
a.repeat(3)
np.concatenate([a,a,a])
np.concatenate([a.repeat(3),np.concatenate([a,a,a])]) 

In [ ]:
#. Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a[a==b])
# MEJOR FORMA
np.intersect1d(a,b)

In [ ]:
#Q. From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
mascara = ( a == np.intersect1d(a,b))
mascara
print(a[mascara == False])
# MEJOR FORMA
np.setdiff1d(a,b)


In [ ]:
#Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)


In [ ]:
# Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
mascara = ((a > 5) & (a <= 10))
a[mascara]

In [ ]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
indices = np.where(np.greater(a,b))
indices[0][1]
for ind in list(indices[0]):
    print(ind)

In [ ]:
# Convert the function maxx that works on two scalars, to work on two arrays.

def pair_maxx(x, y):
    indices = np.where(np.greater(a,b))
    for ind in list(indices[0]):
        print(ind)
        b[ind] = a[ind]
    return b



In [ ]:
 print(pair_maxx(a,b))


In [ ]:
# MEJOR FORMA
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

In [ ]:
pair_max(a,b)

In [ ]:
#Swap rows 1 and 2 in the array arr:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

In [ ]:
#Reverse the rows of a 2D array arr
arr = np.arange(9).reshape(3,3)
arr[::-1]

In [ ]:
# Reverse the columns of a 2D array arr.
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

In [ ]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
arran = np.random.uniform(5,10,(5,3))
np.set_printoptions(3)
arran

In [ ]:
#Limit the number of items printed in python numpy array a to a maximum of 6 elements.
a = np.arange(15)
np.set_printoptions(threshold=100)
a


In [ ]:
#### 3. Create a null vector of size 10 (★☆☆)
arrn = np.full(10,fill_value=np.nan)
arrn

In [ ]:
#### 3. Create a null vector of size 10 (★☆☆)
# que hace esto arrn.__sizeof__() ?
arrn.__sizeof__()

In [ ]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
help(np)

In [377]:
arrn[4] = 1
arrn

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

In [383]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
a = np.random.randint(2,30,10)
a

array([ 3,  3, 13, 27,  9, 13, 15, 22,  7, 20])

In [393]:
a[::-1]


array([20,  7, 22, 15, 13,  9, 27,  0,  3,  3])

In [387]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matriz = np.arange(0,9).reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [395]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
np.where(a==0)

(array([2], dtype=int64),)

In [416]:
#### 11. Create a 3x3 identity matrix (★☆☆)
ident  =np.identity(3)
ident


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [423]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
cubo = np.random.randint(4,29,(3,9))
cubo.reshape(3,3,3)

array([[[15, 27, 19],
        [16, 26, 11],
        [25, 20,  8]],

       [[17, 18, 23],
        [14, 28,  5],
        [14, 21, 19]],

       [[ 6, 12, 24],
        [22,  5, 23],
        [18, 12, 26]]])

In [428]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
matrix = np.random.uniform(1,20,(10,10))
print(f'Maximo:{np.max(matrix)}, Minimo:{np.min(matrix)}')

Maximo:19.881152975492828, Minimo:1.5347795646713616
